directory = "downloads"
concurrency = 5

# Should be kept empty  even if you don't use any login required modules 
logins = {}

[modules.tidal]
username = "meow"
password = "meow"

[modules.qobuz]
username = "meow"
password = "meow"

# ... same for logins
